spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livestream_app_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: root
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:hungndgbh210504@fpt.edu.vn}
    password: ${MAIL_PASSWORD:noddkintjcmhnbjn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.java.live_hungbao: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  email:
    from: noreply@gmail.com
    from-name: Livestream App
    verification-url: http://localhost:3000/verify-email
    reset-password-url: http://localhost:3000/reset-password

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080
      - http://127.0.0.1:3000